### ISSUE TITLE
Further development of the lib

### ISSUE THREAD

**Issue by KOLANICH** [sashs/filebytes#16]
Hi again.

When developing a tool [FrozenTable.py](https://gitlab.com/KOLANICH/FrozenTable.py) editing a data structure in cpython binaries, I had to create some modules it may make some sense to integrate them into your tool

* [BinPatchTools](https://gitlab.com/KOLANICH/FrozenTable.py/tree/master/FrozenTable/BinPatchTools) - an abstraction layer providing an unified interface to some libs for parsing and editing binaries.  Surprisingly even LIEF doesn't, even though it was one of the goals of that project. It may make sense to throw away own parsers used in filebytes and use third-party ones, concentrating on providing a unified interface.
* [ELFRelocs.py](https://gitlab.com/KOLANICH/ELFRelocs.py) - unfortunately none of the libs I have encountered was able to calculate relocs. So I had created a lib allowing integration of relocs computation in third-party libs.
* [ELFMachine.py](https://gitlab.com/KOLANICH/ELFMachine.py) - just a enum for e_machine header field. Different libs use own enum classes, this is bad for interoperability, so I have created a one class to rule them all. `setup.py` visits some hardcoded addresses of projects under permissive licenses and parses this enum from their sources and creates a python file.

**Comment by sashs** [comment]
Hi,

what do you mean with integrate? Do you mean the classes should be reimplemented by using your modules?

**Comment by KOLANICH** [comment]
>what do you mean with integrate?

I mean to add my abstraction layer to your lib, blend the code and merge the classes. Remove everything redundant, taking the best impl available.

**Comment by sashs** [comment]
The idea behind filebytes is to have no further dependencies. I implemented this lib for ropper since there was no other lib that fit to my needs. 
If you want you can implement some functionality in my modules, but it is important to have no dependencies.

**Comment by KOLANICH** [comment]
>If you want you can implement some functionality in my modules, but it is important to have no dependencies.

Are "vendorized" ( copied into the module dir) dependencies counted as dependencies?

**Comment by sashs** [comment]
I would suggest clone the repo and show me what you mean. Just copy your modules into this repo does not make sense. However, your ExecutableFormat class could be merged with the Binary class. 
Your ELFMachine.py Module has other external dependencies.
