### ISSUE TITLE
Installation issues with pip

### ISSUE THREAD

**Issue by TazWake** [sashs/filebytes#19]
I've been trying to install this for two days now and keep hitting errors.

When I try to install this via pip "pip install filebytes", I get the following error message:
```
ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-rjhyqG/filebytes/setup.py", line 15, in <module>
        version = extractMetaInfo((currentDir / "filebytes" / "__init__.py").read_text())["VERSION"]
    AttributeError: 'PosixPath' object has no attribute 'read_text'
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-rjhyqG/filebytes/

```
I've tried updating setuptools etc, but it still doesnt work. I am not sure if this is a problem with pip or filebytes though.

**Comment by sashs** [comment]
Hi,

this issue only exists with python2. However, it is fixed in the master branch, but not uploaded to the pip server.

It is a dependency problem which comes with a pull request. The setup.py uses pathlib and pathlib for python2 does not support the method read_text.

**Comment by TazWake** [comment]
Thanks - it works when I pull the repo and install via setup.py, as you've said here.
