### ISSUE TITLE
How convert bytes(elf) to filebytes.elf.ELF format? 

### ISSUE THREAD

**Issue by yougwypf1991** [sashs/filebytes#22]
Now I get bytes data(from elf file) from network, I want to analysis it use filebytes, so how convert bytes format to filebytes.elf.ELF format?

**Comment by sashs** [comment]
Hi,

```
from filebytes.elf import ELF

b = read_bytes_from_network()
elf = ELF('any name', b)
```

**Comment by sashs** [comment]
As shown here: https://scoding.de/filebytes-introduction

**Comment by yougwypf1991** [comment]
Thank you very much.
