### ISSUE TITLE
"Buffer size too small" with a Xcode DWARF file

### ISSUE THREAD

**Issue by sevaa** [sashs/filebytes#23]
Trying to open a DWARF debug symbols file, as generated by Xcode on Mac, with filebytes.MachO. Getting the following error message from the MachO constructor:

> `>>>` macho = MachO(filename)
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/seva/.local/lib/python2.7/site-packages/filebytes/mach_o.py", line 365, in __init__
>     self.__fatArches = self._tryParseFat(self._bytes)
>   File "/home/seva/.local/lib/python2.7/site-packages/filebytes/mach_o.py", line 438, in _tryParseFat
>     thin = MachO('{}.{}'.format(self.fileName, cputype), thin_data)
>   File "/home/seva/.local/lib/python2.7/site-packages/filebytes/mach_o.py", line 374, in __init__
>     self.__loadCommands = self._parseLoadCommands(self._bytes, self.machHeader)
>   File "/home/seva/.local/lib/python2.7/site-packages/filebytes/mach_o.py", line 461, in _parseLoadCommands
>     command = self.__parseSegmentCommand(data, offset, raw)
>   File "/home/seva/.local/lib/python2.7/site-packages/filebytes/mach_o.py", line 481, in __parseSegmentCommand
>     sections = self.__parseSections(data, sc, offset+sizeof(self._classes.SegmentCommand))
>   File "/home/seva/.local/lib/python2.7/site-packages/filebytes/mach_o.py", line 522, in __parseSections
>     raw = (c_ubyte * sec.size).from_buffer(data, sec.offset)
>     ValueError: Buffer size too small (2089089 instead of at least 2406496 bytes)   

Looks like some kind of assumption about section size doesn't hold. What should I check?

DWARFDUMP on Mac has no problem with that file.

**Comment by sashs** [comment]
Hey, 
I assume something is parsed wrong. Could you provide a sample file?

**Comment by sevaa** [comment]
[ym.zip](https://github.com/sashs/filebytes/files/4006302/ym.zip)
Try this one.
