### ISSUE TITLE
Support Apple Universal Binary

### ISSUE THREAD

**Issue by mazegen** [sashs/filebytes#9]
First of all, thank you for this great project!

Would it be possible to add support for Universal binaries that are frequently used on iOS (armv7 and arm64 binary), for example? The header is defined in `fat.h`, it is the `fat_header` struct.

**Comment by sashs** [comment]
Hi, 

thank you. I want to implement it, however, I have very little time at the moment.

**Comment by mazegen** [comment]
My quick'n'dirty code, if it helps.

	# read magic value
	# see also struct fat_header in MachO docs

        magic = bytearray(data)[:4]

	# fat binary?

	if magic == p('>I', 0xCAFEBABE):
		nfat_arch_array = bytearray(data)[4:8]
		nfat_arch_array_str = "".join("%02x" % b for b in nfat_arch_array)
		print(nfat_arch_array_str)
		nfat_arch = struct.unpack(">I", nfat_arch_array)[0]

		# see also struct fat_arch in MachO docs

		base = 8   # sizeof fat_header

		for _ in range(nfat_arch):
			cputype_array = bytearray(data)[base:base+4]
			cputype = struct.unpack(">I", cputype_array)[0]
			offset_array = bytearray(data)[base+4+4:base+4+4+4]
			offset = struct.unpack(">I", offset_array)[0]
			size_array = bytearray(data)[base+4+4+4:base+4+4+4+4]
			size = struct.unpack(">I", size_array)[0]

			print("cputype {}, offset {} ({}), size {} ({})".format(CpuType[cputype], hex(offset), offset, hex(size), size))

			tada = data[offset:offset+size]

			base += 5*4   # sizeof fat_arch
	else:
		print("fat binary was not detected")

**Comment by sashs** [comment]
Hey,
thank you for this snippet. Sorry for the delay. I am currently too busy to implement that filetype. I will implement it as soon as I can.

**Comment by sashs** [comment]
Is implemented now. 
Thank you, @rsesek !
